version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:8000"
      - "443:443"
    volumes:
      - ./app/data:/app/app/data
      - ./certs:/etc/letsencrypt
    environment:
      - DOMAIN=netpulse.space
      - EMAIL=pplyuvkov@gmail.com
      - APP_ENV=production
    restart: unless-stopped
    command: /bin/sh -c "chmod +x /app/init-letsencrypt.sh && /app/init-letsencrypt.sh && uvicorn app.endpoint:app --host 0.0.0.0 --port 443 --ssl-keyfile /etc/letsencrypt/live/$$DOMAIN/privkey.pem --ssl-certfile /etc/letsencrypt/live/$$DOMAIN/fullchain.pem"